#!/bin/bash

# Make the concrete file...
#
#  cd to the directory with your docker-compose.yml file
#  mkdir helpers ; cd helpers
#
#  !!! In below, replace --name-- with the <NAME> of the service. e.g. devenv-<NAME>
#  sed -e "s#<PATH>#${PWD}#" -e 's/<NAME>/--name--/' /path/to/runWithDockerRun-TEMPLATE > runWithDockerRun
#
#  chmod a+x runWithDockerRun

#  Make the symbolic links
#  for i in cmake g++ gcc make; do ln -s runWithDockerRun $i ; done
#
#  Need a real copy for your <EXP> executable (replace <EXP> with that, e.g. nova, gm2, etc)
#    because CLion will insist on resolving the synbolic link to the target
#  cp runWithDockerRun <EXP>

command=$(basename "$0")

if [[ $(uname -s) == Darwin ]]; then
  docker-compose -f <PATH>/../docker-compose.yml run --rm -T --no-deps -w "$PWD" devenv-client-<NAME> $command "$@"
else
  $command "$@"
fi
